### PR TITLE
resized and repositioned logo svg file in the header component

### LINKED ISSUE #23: Header component

### PR DESCRIPTION
**Pull request by dumpidum**
resized and repositioned logo svg file in the header component

### CODE REVIEW

**Review by Sanlung — COMMENTED** [review]
Hey, Ignat. that's not how you handle a svg file, or style a Logo component. But I guess it involves Asel who has not made a Next image component for the logo, or use React to make it a Logo component that imports the logo svg file from the /public/images/ folder. We'll discussed these in the next brief.

**Review by Sanlung — CHANGES_REQUESTED** [review]
Forgot to request changes in the previous review.

**Comment by siirila** [comment]
This is a valid, but different way, to handle svg files in React. You can either treat them like other image resources and load them from image files directly or embed the svg markup directly in a React component and render it that way. There are pros and cons to each approach.

**Comment by dumpidum** [comment]
Unnecessary PR.

**Pull request closed without merging**
