### PR TITLE
Added ListPane to wrap LoggedIn and List components and Implemented Next.js routing and React states for the app

### LINKED ISSUE #31: Next.js routing
The app uses Next.js dynamic routes. The home page (/index.js and Home component) serves the login page that renders a Login component and nested components that make up the login/sign-up form. When a user is authenticated the Home compo directs an imperative route (router.push()) to render the /pages/user/index.js page that has the Sidebar and an empty list field with background and some placeholder content. When the user click on a todo list on the Sidebar it'll direct an imperative route to render the /pages/user/[list].js page that displays the list along side Sidebar. The two dynamic routes need be implemented to have the app work as a single page app.

### PR DESCRIPTION
**Pull request by Sanlung**
The LoggedIn component (at "/pages/user") need placeholder contents, e.g., background, pictorials, a message, etc., because it renders along the Sidebar component when a user is logged in, but does not have a todo list to show before the user clicks a todo list in the Sidebar to display it. Once the user click a list in the Sidebar, however, the link takes it to another page at "/pages/user/[list].js" that is the ListPane component which dsplays the list. So to have a common background for the LoggedIn and ListPane components I propose a ListBackground component, which will be used to provide a background video under a gradient background color and contains some static content for the LoggedIn component and the TodoList for the ListPane component.

### CODE REVIEW

**Review by Asel-K — COMMENTED** [review]
Looks ok to me.

**Comment by Sanlung** [comment]
So as I posted on Slack, the app works with all the routes now with states in Sidebar and List (`/pages/user/[list].js`) fetched from Firestore each time a route is triggered. Our app now has a common platform for the team to work on testing areas within each person's responsibility. Please review and approve so we can finally move forward concentrating on how to implement the various features without having to bother with mocking the routes and states.

**Review by Asel-K — APPROVED** [review]
This is really helpful! You've done a lot of work!

**Comment by Sanlung** [comment]
> This is really helpful! You've done a lot of work!

Got a minor bug and fixed it: the unnecessary useCallback hook in Sidebar. Rid of it with the new commit.

**Review by dumpidum — APPROVED** [review]
Looks great. You've done a lot!

**Pull request merged**
